controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    reference_timeout: 2.0
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    traction_joints_names: [re_right_wheel_joint, re_left_wheel_joint]
    steering_joints_names: [fr_right_steer_joint, fr_left_steer_joint]

    wheelbase: 0.25
    traction_track_width: 0.15
    traction_wheels_radius: 0.022


    # publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    # base_frame_id: base_link

    # left_wheel_names: ['re_left_wheel_joint']
    # right_wheel_names: ['re_right_wheel_joint']
    # wheel_separation: 0.3
    # wheel_radius: 0.14

    # use_stamped_vel: false